[build]
builder = "dockerfile"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT --log-level info"
healthcheckPath = "/"
healthcheckTimeout = 600
healthcheckInterval = 30
healthcheckGracePeriod = 120
healthcheckRetries = 10
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[variables]
PORT = "8000"
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"
